### ISSUE TITLE
Improve Library

### ISSUE THREAD

**Issue by crisap94** [SensorsIot/NTPtimeESP#1]
Hi Andreas i am a follower of you, i've been watching all your videos since 1 year ago , I'm working with the ESP and i have worked with NTP, and the library you have made is a little bit simple, i would like to improve it.

What do you have on mind for improving the library?
Can you put the "TO DO" list in the README?

Using the Time.h and this you get nice functions to manage time.

Regards.

**Comment by SensorsIot** [comment]
I hope, you got access to my repository. I am not a frequent Githup user and do not know its functionality. But feel free to upgrade the library.

**Comment by crisap94** [comment]
Hi Andreas, thanks for the acces, i would like to know what would you like
to improve.

I have some ideas for debuggin and memory, would be nice to discuss other
point like scheduling or other things like that.

Or make a more friendly Library

Regards.
Cristian

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=cristianisaac94@gmail.com&idSignature=22

2016-08-01 1:05 GMT-05:00 SensorsIOT notifications@github.com:

**Comment by SensorsIot** [comment]
You can implement whatever you want. Just describe it
You find also another library which uses the SNTP protocol in my github.
I will use this library to create a daily task where the ESP sleeps 24h and executes a task at a particular time every day. Due on Thursday.

**Comment by lucaberta** [comment]
Hi @crisap94, have you done any further work on this library, like you mentioned in this exchange with @SensorsIot from 2 months ago?

Bye, Luca

**Comment by crisap94** [comment]
I used it for a College Project where it became in a software component for the DS3231. New implementations with the time library, but cannot upload it to the repo, it diverge too much,  i need to clean the code and upload it. thanks for keeping in touch @lucaberta .
