### ISSUE TITLE
DEBUG doesn't work and it fails oftenly to retrieve dateTime

### ISSUE THREAD

**Issue by bogdanr** [SensorsIot/NTPtimeESP#11]
Hello,

I have this sketch which is pretty much as the example:
```cpp
#include <NTPtimeESP.h>

#define DEBUG_ON


NTPtime NTPch("ch.pool.ntp.org");   // Choose server pool as required
char *ssid      = "obviously";         // Set you WiFi SSID
char *password  = "fake";                 // Set you WiFi password

strDateTime dateTime;

void setup() {
  Serial.begin(115200);
  Serial.println("Connecting to Wi-Fi");

  WiFi.mode(WIFI_STA);
  WiFi.begin (ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }
  Serial.println("WiFi connected");
}

void loop() {

  dateTime = NTPch.getNTPtime(1.0, 1);

  // check dateTime.valid before using the returned time
  // Use "setSendInterval" or "setRecvTimeout" if required
  if (dateTime.valid) {
    NTPch.printDateTime(dateTime);

    byte actualHour = dateTime.hour;
    byte actualMinute = dateTime.minute;
  } else {
    Serial.println("Failed to get a valid dateTime");;
  }
  delay(20000);
}
```
Now my serial output looks like this:
```
Connecting to Wi-Fi
...WiFi connected
Failed to get a valid dateTime
2017-7-2-1 12H 4M 41S 
Failed to get a valid dateTime
2017-7-2-1 12H 5M 21S 
Failed to get a valid dateTime
2017-7-2-1 12H 6M 1S 
Failed to get a valid dateTime
2017-7-2-1 12H 6M 41S 
Failed to get a valid dateTime
2017-7-2-1 12H 7M 21S 
Failed to get a valid dateTime
2017-7-2-1 12H 8M 1S 
Failed to get a valid dateTime
```

I see two issues here:
1. It fails often to retrieve valid dateTime. Increasing the delay doesn't seem to help.
2. DEBUG_ON doesn't print additional data.

I am using Arduino 1.8.2

Using a version before commit https://github.com/SensorsIot/NTPtimeESP/commit/3947d98ed2a4e566d59297a0ffd3014598730bfc seems to retrieve dateTime more reliably.

**Comment by frownbreaker** [comment]
Have you checked your DNS setting and run wireshark. I installed the code and it works fine.
UDP is not guaranteed delivery so you need to check you network is working for UDP on the NTP port.
Also DNS is needed to resolve the NTP server name if that does not resolve reliable that might explain what you are seeing? Do you have examples that work with older versions and not the newer version on your current network? I think you should try the device on a known good network GRC.COM has a good DNS test program. ISP provide really bad DNS on the whole try Google DNS 8.8.8.8 and report back your findings.

Might also be prudent to use a local timeserver in case the NTP server is overloaded or the round trip is flakey for UDP.  For example in the uk "0.uk.pool.ntp.org" will work well as the ISP and traffic is well know / used I find this more reliable than the Swiss NTP for myself in London.

DDOS and other nasty activity can use UDP so transnational UDP for NTP may be impacted by ISPs. Also if you have high traffic UDP (Torrents / VPN) on your network and are running consumer grade network kit UDP dropout or blind spots for slow devices are common.

**Comment by bogdanr** [comment]
DNS is definitely not the issue because my router is also caching the response.

I tried different timeservers and it's absolutely no difference in reliability.

I made a small change in code so it automatically retries when it's failing, but with a small delay:
```cpp
void getShowData() {
  dateTime = NTPch.getNTPtime(2.0, 1);  // +2GMT with summer time.

  if(dateTime.valid){
    NTPch.printDateTime(dateTime);
  } else {
    Serial.println("We did not retrieve valid dateTime");
    delay(100);  // adding this delay make the function work 100% reliable on the subsequent try.
    getShowData();
  }
}
```
and it's always succeeds on the second try. Without the delay it fails 6-10 times until it works.
This is an indication for me it has to do with some timing. Before the commit that made the code non-blocking it used to work every time.

Also, there is the issue that DEBUG_ON doesn't do anything for me but that's a different story.

**Comment by OipRDDinoSaric** [comment]
I have the same problem. Experiencing the same thing as you with your code.

**Comment by iariza1** [comment]
The same problem

**Comment by neutronixx** [comment]
The same problem

**Comment by SensorsIot** [comment]
Unfortunately I cannot do remote consulting :-(
