### ISSUE TITLE
Zeitfehler nach ein paar Minuten Laufzeit 

### ISSUE THREAD

**Issue by dr-apple** [SensorsIot/NTPtimeESP#14]
Die Lib funktioniert ein paar Minuten einwandfrei, aber dann bleibt sie mit 7:28:16 - 7-2-2036 stehen ?

Was läuft da falsch ?

**Comment by philchamp51** [comment]
Hello. I have the same problem. The Lib works well for a few minutes and after it blocks at 07:28:16 - 7-2-2036 for about 3 minutes and so on, it works, it blocks, it works, it blocks and always with this same time 07:28:16 - 7-2-2036.
Do you have any idea about this problem?

**Comment by SensorsIot** [comment]
Ich vermute, dein Device kriegt von Zeit zu Zeit keine Antwort vom Time Server. Vielleicht fügst du ein Print statement ein um das zu überprüfen.

**Comment by dr-apple** [comment]
Hi Danke für deine Antwort, ich habe viele NTP Libs versucht alle gehen dauerhaft, aber sind sehr komplex, deswegen wollte ich deine verwenden, aber nur bei dieser Lib passiert das ???

**Comment by LeqitDev** [comment]
Hab das gleiche problem...
Sonst nice lib

**Comment by underwoodblog** [comment]
@dr-apple wie oft fragst Du denn dien Zeitserver ab? Schon mal einen anderen Zeitserver probiert?

**Comment by dr-apple** [comment]
Hi ja klar ich habe die Fritzbox versucht und mind. 3 weitere immer das selbe ;-(

**Comment by SensorsIot** [comment]
Die Library wird sehr oft gebraucht. Deshalb weiss ich nicht, wieso sie bei dir nicht fonktioniert. Es geht allerdings eine Zeit bis du Antwort bekommst. und wenn diese Zeit nicht ausreichst bricht die Lib vorher ab...
