### ISSUE TITLE
Enhancement : Offset in timezone

### ISSUE THREAD

**Issue by mohitverma123** [SensorsIot/NTPtimeESP#2]
Hi Andreas,

Thanks for the amazing library. Wanted to suggest an improvement.  You have declared the timzone as an int, we can convert it to float, so that it work with 30mins offsets like in India we have timezone offset of +5hrs,30mins
Or you can add a offset variable to the adjust timezone. 

I personally converted the timezone to float everywhere and it works flawlessly.

Thanks again for you work

**Comment by SensorsIot** [comment]
Done

**Comment by sonukushwah221** [comment]
can you share the offset value for Indian Time

**Comment by sonukushwah221** [comment]
Ok , I add 5.5 in this NTPch.getNTPtime(5.5,0);

Thanks
