### ISSUE TITLE
clearficition needed on the example

### ISSUE THREAD

**Issue by mai95** [SensorsIot/NTPtimeESP#22]
in the [comment ](https://github.com/SensorsIot/NTPtimeESP/blob/c6a2e6e063789d8c20e58da1d1d4d8613b47dab1/examples/NTPtimeESP/NTPtimeESP.ino#L2) data will be sent every day
but i did`t get  where is the line in charge of that
i want to send data every 30 minutes to Firebase 
### do you think it`s possible ?

**Comment by underwoodblog** [comment]
The comment seems wrong. As far as I see, it only prints the time on serial console.

I don't think you need the excact absolute time, you can work with a simple 30min timer. Take a look at **Ticker.h**
