### ISSUE TITLE
is there an offline comment to call once time has been fetched?

### ISSUE THREAD

**Issue by laurentopia** [SensorsIot/NTPtimeESP#24]
getNTPtime fetches time from the server, once a second is a bit excessive as a clock.
What's the command to call and get time once NTP has been fetched?

**Comment by TheFern2** [comment]
The library defaults are for 1sec, and max 60secs. However you can read the NTPtimeESP.cpp, and see for yourself that you can set those times yourself.

As stated on the example code:

setSendInterval, and setRecvTimeout

```
class NTPtime {
  public:
    NTPtime(String NTPtime);
    strDateTime getNTPtime(float _timeZone, int _DayLightSaving);
    void printDateTime(strDateTime _dateTime);
    bool setSendInterval(unsigned long _sendInterval);  // in seconds
    bool setRecvTimeout(unsigned long _recvTimeout);    // in seconds
```
