### ISSUE TITLE
Time change weekend wrong 

### ISSUE THREAD

**Issue by davidginn524** [SensorsIot/NTPtimeESP#26]
Hello
First of all let me say I love all your videos. They are very informative. 
Currently I am trying to use this libarary for a word clock. So far it is working well. HOWEVER
I was looking into your code/comments and it appears that the DST is being calulated for the middle of march and first of november. However all Europe is 31st of march for the time change this year. 
Then when DST ends , it's ending on Oct 27th not the first week in November :(

**Comment by SensorsIot** [comment]
DST is for the Americas. In Europe, it is called Summer Time and it should have a different formula in the library.

**Comment by davidginn524** [comment]
ahh sorry about that I misunderstood that. many thanks for following up on that
