### ISSUE TITLE
'setSendInterval' was not declared in this scope

### ISSUE THREAD

**Issue by MHz000** [SensorsIot/NTPtimeESP#30]
try to set the NTP query interval by adding:
     unsigned long NTPrequest = 600;
    setSendInterval(NTPrequest);          // NTP request every x seconds
to the sample code. 
yields 'setSendInterval' was not declared in this scope.
How to do this the correct way?

in between NTP requests is the "internal" RTC running an can be read by
   if(dateTime.valid){
      NTPif(dateTime.valid){
     ch.printDateTime(dateTime);  
    ....)

**Comment by SensorsIot** [comment]
you have to use NTPch.setSendInterval().

**Comment by MHz000** [comment]
Thank you for answering my question, 
however it dosn't solve the problem :-(
see source code
 and what about the second part of my question?
Thank you!
-------------------------- schnipp ----------------------------------------
#include <NTPtimeESP.h>
#define DEBUG_ON
NTPtime NTPch("ch.pool.ntp.org");   // Choose server pool as required
char *ssid      = "";               // Set you WiFi SSID
char *password  = "";               // Set you WiFi password
/*
 * The structure contains following fields:
 * struct strDateTime
{
  byte hour;
  byte minute;
  byte second;
  int year;
  byte month;
  byte day;
  byte dayofWeek;
  boolean valid;
};
 */
strDateTime dateTime;
void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println("Booted");
  Serial.println("Connecting to Wi-Fi");

  WiFi.mode(WIFI_STA);
  WiFi.begin ("****", "****");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }
  Serial.println("WiFi connected");  
//  setSendInterval(60);                //  not working: NTP request interval   
  NTPch.set(60);                            //  not working too
}

void loop() {
  // first parameter: Time zone; second parameter: 1 for European summer time; 2 for US daylight saving time; 
  dateTime = NTPch.getNTPtime(1.0, 1);
  // check dateTime.valid before using the returned time
  // Use "setSendInterval" or "setRecvTimeout" if required
  if(dateTime.valid){
    NTPch.printDateTime(dateTime);
    byte actualHour = dateTime.hour;
    byte actualMinute = dateTime.minute;
    byte actualsecond = dateTime.second;
    int actualyear = dateTime.year;
    byte actualMonth = dateTime.month;
    byte actualday =dateTime.day;
    byte actualdayofWeek = dateTime.dayofWeek;
  }
  delay(10000);
}
