### ISSUE TITLE
Could I use it in other place?

### ISSUE THREAD

**Issue by ShengXingyu** [SensorsIot/NTPtimeESP#31]
Could I use it in other place? Such as Asia?

**Comment by GTP95** [comment]
Of course you can, just select another NTP pool. You can look on Google for the closest pool to your area.

**Comment by davidginn524** [comment]
Had a question on NTP pools. If I specify a generic pool such as pool.ntp.org. Will it get the closest NTP server to my location? 
For example If I specify pool.ntp.org and I setup the clock in the UK it will work off the closest one there. Then I decide to move over to the USA and it still uses pool.ntp.org does it find the closest one there then? 
I know I could specify one such as uk.pool.ntp.org and it will choose one of those from the UK pool but thought if it would be more generic it will automaticlaly do that? 
My guess is this library wont do that but the NTP Server might automatically do this?

**Comment by GTP95** [comment]
You should open a new issue for this.

**Comment by SensorsIot** [comment]
I assume the pool server does the assignment. So you have to ask them what strategy they follow.
