### ISSUE TITLE
conficting scan

### ISSUE THREAD

**Issue by fungreenfox** [SensorsIot/NTPtimeESP#33]
While the use of NTPtimeESP.h

For the Si4703 radio module, these lines are for RDS receiving. 
exit status 1
**conflicting declaration 'SCAN_STATE state'** Which means, "can not have a simulated clock with the use of NTPtimeESP.h
 if RDS receiving with Si4703.h is wanted"

```
/// State definition for this radio implementation.
enum SCAN_STATE {
  STATE_START,      ///< waiting for a new command character.
  STATE_NEWFREQ,
  STATE_WAITFIXED,
  STATE_WAITRDS,
  STATE_PRINT,
  STATE_END          ///< executing the command.
}; // (Semicolon intended)

SCAN_STATE state; ///< The state variable is used for parsing input characters.
uint16_t g_block1; uint16_t g_block2; uint16_t g_block3; uint16_t g_block4;

void RDS_process(uint16_t block1, uint16_t block2, uint16_t block3, uint16_t block4)
{
  g_block1 = block1;
  rds.processData(block1, block2, block3, block4);
}
```

**Comment by SensorsIot** [comment]
Are you sure this is the right place for this issue? This project does not use an Si4703 radio module.

**Comment by fungreenfox** [comment]
okay, the NTPtimeESP.h code used for a clock simulate example, and i thought this came with the NTPtimeESP.h library, which is conflicting with the si4703.h (RDS part), of what can be told from the compiler.
