### ISSUE TITLE
same time several times

### ISSUE THREAD

**Issue by GitJer** [SensorsIot/NTPtimeESP#4]
I tried the example with a delay of 20s and noticed it printed the same time a couple of times in a row, then reported the correct time and displayed that for a couple of times. After some debugging I was able to always get the correct time if I changed one line in NTPtime::adjustTimeZone:

_timeStamp += (int)(_timeZone \*  3600.); // adjust timezone

Regards,
Jeroen.

**Comment by lucaberta** [comment]
@GitJer I have just tried to decrease the delay to 5 seconds, and I do not see any issue with duplicate time strings.

The modification from int to unsigned long was done to support cases such as India and certain parts of Canada, where there is a 30 minutes delta in the local timezone, and the int would not support such cases. It has been discussed in issue #2.

Bye, Luca

**Comment by GitJer** [comment]
I think the problem might be due to a difference between windows and linux.
