### ISSUE TITLE
.sending NTP packet...  comes randomly

### ISSUE THREAD

**Issue by lanoph** [SensorsIot/NTPtimeESP#5]
Hello.
I want to use your library and it looked really nice to use.
But I couldn´t get it to work.
even when I upload the example sketch to my ESP8266-12E the serial monitor shows the follwing:
...
WiFi connected
IP address: 192.168.170.99
Waiting for NTP packet
0.0.0.0
sending NTP packet...
.sending NTP packet...
.sending NTP packet...
.sending NTP packet...
.sending NTP packet...
.sending NTP packet...
.sending NTP packet...     this does never end.

What is my misstake? can anyone help me? 
I also tried to cahnge the NTP-Server-Pool address.
Thanks in advance for a short answer.

Lanoph

**Comment by lucaberta** [comment]
Hi @lanoph, it appears that your code is sending NTP packets to the 0.0.0.0 address, which of course is not a valid NTP server address.

Have you kept the same server DNS name which is in the original code, "ch.pool.ntp.org", or you have changed it?

The code works for me, and each packet is sent to a different address, meaning that a new DNS resolution is performed each time, and thus the NTP pool list answers to the DNS query with a different server.

You can also hardwire the IP address of an NTP server if you want, just put it within quotes in lieu of the "ch.pool.ntp.org" entry.

HTH, Luca

**Comment by middelbh** [comment]
Hi Luca,

I have the same problem as described by Lanoph, I used your lib for some weeks now without any problem, but starting this weekend I got exactly the same problems without having changed anything... I used both ch.pool.ntp.org and nl.pool.ntp.org with the same results..
I would like to try your proposal, but cannot find the IP address of a NTP server close by.

Thanks for your reply!

Hans

**Comment by lucaberta** [comment]
Dag Hans @middelbh

what's strange in your case is that things worked, and then stopped!

It also looks like a DNS resolution issue to me.

As a test, you might want to use one of the IP addresses of NTP servers in the nl.pool.ntp.org pool:

`nl.pool.ntp.org.   105 IN  A   87.253.148.92`
`nl.pool.ntp.org.   105 IN  A   195.242.98.57`
`nl.pool.ntp.org.   105 IN  A   88.159.1.197`
`nl.pool.ntp.org.   105 IN  A   178.239.61.38`

Beware the fact that hardwiring in source code an IP address of a service which can change over time is never a good thing to do, especially when updating the firmware can be a complicated thing to do!

MvG,

Luca

**Comment by middelbh** [comment]
Hallo Luca,

I tried 178.239.61.38 with exactly the same result. Must be something else in my system I'm afraid. 
I am using it on an ESP8266 but suddenly did have some problems with uploading using esptool.exe this weekend. So not changing the sketch, but the IDE environment.. 
I will have to check further!

Groetjes, Hans

**Comment by middelbh** [comment]
Hi Luca,

Success now! To load my sketch to the ESP I used an older version of esptool.exe, as my viruschecker deleted the newest one, (contained a Trojan it said).
I am happy again!

Hans

**Comment by lanoph** [comment]
Hello again,
I still have the same problem.
I checked everything: NTP-Adress, and anything else.
I want to use it as a Library which I will upload throught the arduino IDE to an ESP8266-12E.
Maybe this is the problem. Can anyone help me?
I can upload the ohther NTP-Time-Librarys. They work, but I want to use this, because it hase the bulid-in Timezone and DaySaving-Funtion.
Thanks in advance.
Lanoph

**Comment by middelbh** [comment]
Lanoph,

I did not describe my solution correct. I had the problem as you did when I used an older version of esptool.exe as my viruschecker did not accept the newest version. After install of the newest version from 2016 and telling my viruschecker that it does not contain a trojan the problem was solved. So maybe you should check the version of esptool.exe on your system.
Hans

**Comment by SensorsIot** [comment]
Maybe you try my other library: https://github.com/SensorsIot/SNTPtime
It uses another call to the NTP servers

**Comment by underwoodblog** [comment]
@lanoph this is realy weird. I use the actual Arduino IDE with an ESP-01 and it works without any problems.  Is your WLAN and internet connection ok? Can you ping the time server from your local computer? Maby you could try another time server **"time.google.com"**. If you have a FritzBox, you can configure it to get the time and act like a local time server to whom you connect with your ESP if you have problems connect to the internet.
