### ISSUE TITLE
#define DEBUG_ON in example code

### ISSUE THREAD

**Issue by underwoodblog** [SensorsIot/NTPtimeESP#7]
This is not a real issue, only a suggestion: 

I think it is better, to remove or comment out the **#define DEBUG_ON** from _**NTPtimeESP.h**_ and put it in the example code. I know I can edit it myself but it's there again with a future release and than I may get problems with my code, because it writes more serial data than expected.

**Comment by SensorsIot** [comment]
Thanks for the feedback. Done.
